### ISSUE TITLE
Abilities incorrectly applied with multiple associations to the same model

### ISSUE THREAD

**Issue by kbrandwijk** [CanCanCommunity/cancancan#523] opened 2018-08-15 17:35 UTC
### Steps to reproduce

Given these models:
```ruby
class Account < ApplicationRecord
end

class Project < ApplicationRecord
  belongs_to :manager, class_name: 'Account'
  belongs_to :client, class_name: 'Account'
end
```
And these ability config:
```ruby
can :read, Project, manager: { name: user.name }
can :read, Project, client: { name: user.name }
```

Run this query
```ruby
Project.accessible_by(ability).first
```

### Expected behavior
I should only be able to see Projects where I am either the manager _or_ the client

### Actual behavior
The generated query only takes the first association into consideration, effectively only returning those Projects where I am the manager.
```sql
SELECT COUNT(DISTINCT "projects"."id") 
FROM "projects" 
LEFT OUTER JOIN "accounts" ON "accounts"."id" = "projects"."manager_id" 
LEFT OUTER JOIN "accounts" "clients_projects" ON "clients_projects"."id" = "projectss"."client_id" 
WHERE (("accounts"."name" = 'John') OR ("accounts"."name" = 'John'))
```
The second where clause should use the alias `clients_projects`. The correct SQL statement is:
```sql
SELECT COUNT(DISTINCT "projects"."id") 
FROM "projects" 
LEFT OUTER JOIN "accounts" ON "accounts"."id" = "projects"."manager_id" 
LEFT OUTER JOIN "accounts" "clients_projects" ON "clients_projects"."id" = "projectss"."client_id" 
WHERE (("accounts"."name" = 'John') OR ("clients_projects"."name" = 'John'))
```

### System configuration
**Rails version**:
5.2.0
**Ruby version**:
2.5.1
**CanCanCan version**
2.2.0

**Comment by jrhicks** [comment] 2018-08-16 14:58
I was able to reproduce this.

**Comment by jrhicks** [comment] 2018-08-16 16:38
Error possibly traced to this line, which always users the table name of the association and not the anticipated aliased name:

https://github.com/CanCanCommunity/cancancan/blob/8fc2a2dbefc542749650da6b957335e8075b34a3/lib/cancan/model_adapters/active_record_adapter.rb#L61

**Comment by coorasse** [comment] 2018-09-02 14:40
duplicate of #337

**Closed by coorasse** 2018-09-02 14:40 UTC
