### ISSUE TITLE
Issue with OR and complex query

### ISSUE THREAD

**Issue by hallmatt** [CanCanCommunity/cancancan#306] opened 2016-03-25 21:03 UTC
I'm having an issue with a complex ability:

``` ruby
  # ability.rb
  can :read, Document, :document_lenders => { :lender_id => user.lender_id }
  can :read, Document, :document_lender_groups => { :lender_group_id => user.lender.lender_group_ids }
```

According to the docs (https://github.com/CanCanCommunity/cancancan/wiki/defining-abilities#combining-abilities), I would imagine these two would work together to form an "OR". Perhaps they're too complex? The statements work well individually, but not together.

Here's the error I'm receiving - notice at the end of the SQL statement where the Ruby hash is injected and not turned into SQL:

```
PG::SyntaxError: ERROR:  syntax error at or near "{"
LINE 1: ..."loans"."id" = "document_loans"."loan_id" WHERE (({:document...
                                                             ^
: SELECT "documents"."id" AS t0_r0, "documents"."title" AS t0_r1, "documents"."file_file_name" AS t0_r2, "documents"."file_content_type" AS t0_r3, "documents"."file_file_size" AS t0_r4, "documents"."file_updated_at" AS t0_r5, "documents"."report_type" AS t0_r6, "documents"."created_at" AS t0_r7, "documents"."updated_at" AS t0_r8, "documents"."guid" AS t0_r9, "document_lenders"."id" AS t1_r0, "document_lenders"."document_id" AS t1_r1, "document_lenders"."lender_id" AS t1_r2, "document_lenders"."created_at" AS t1_r3, "document_lenders"."updated_at" AS t1_r4, "lenders"."id" AS t2_r0, "lenders"."name" AS t2_r1, "lenders"."short_name" AS t2_r2, "lenders"."created_at" AS t2_r3, "lenders"."updated_at" AS t2_r4, "document_lender_groups"."id" AS t3_r0, "document_lender_groups"."lender_group_id" AS t3_r1, "document_lender_groups"."document_id" AS t3_r2, "document_lender_groups"."created_at" AS t3_r3, "document_lender_groups"."updated_at" AS t3_r4, "lender_groups"."id" AS t4_r0, "lender_groups"."name" AS t4_r1, "lender_groups"."created_at" AS t4_r2, "lender_groups"."updated_at" AS t4_r3, "document_loans"."id" AS t5_r0, "document_loans"."document_id" AS t5_r1, "document_loans"."loan_id" AS t5_r2, "document_loans"."created_at" AS t5_r3, "document_loans"."updated_at" AS t5_r4, "loans"."id" AS t6_r0, "loans"."loan_type" AS t6_r1, "loans"."borrower_name" AS t6_r2, "loans"."borrower_type" AS t6_r3, "loans"."property_address" AS t6_r4, "loans"."user_id" AS t6_r5, "loans"."expiration_date" AS t6_r6, "loans"."photo_file_name" AS t6_r7, "loans"."photo_content_type" AS t6_r8, "loans"."photo_file_size" AS t6_r9, "loans"."photo_updated_at" AS t6_r10, "loans"."status" AS t6_r11, "loans"."loan_overview" AS t6_r12, "loans"."summary" AS t6_r13, "loans"."posted_date" AS t6_r14, "loans"."loan_amount" AS t6_r15, "loans"."amount_available" AS t6_r16, "loans"."guarantors" AS t6_r17, "loans"."appraised_value" AS t6_r18, "loans"."proposed_interest_rate" AS t6_r19, "loans"."current_interest_rate" AS t6_r20, "loans"."ltv" AS t6_r21, "loans"."dscr" AS t6_r22, "loans"."required_dscr" AS t6_r23, "loans"."risk_rating" AS t6_r24, "loans"."collateral" AS t6_r25, "loans"."term" AS t6_r26, "loans"."amort" AS t6_r27, "loans"."notes" AS t6_r28, "loans"."mbc_users_to_notify" AS t6_r29, "loans"."created_at" AS t6_r30, "loans"."updated_at" AS t6_r31, "loans"."guid" AS t6_r32, "loans"."type_of_opportunity" AS t6_r33, "loans"."associated_lenders" AS t6_r34, "loans"."associated_lender_groups" AS t6_r35 FROM "documents" LEFT OUTER JOIN "document_lenders" ON "document_lenders"."document_id" = "documents"."id" LEFT OUTER JOIN "lenders" ON "lenders"."id" = "document_lenders"."lender_id" LEFT OUTER JOIN "document_lender_groups" ON "document_lender_groups"."document_id" = "documents"."id" LEFT OUTER JOIN "lender_groups" ON "lender_groups"."id" = "document_lender_groups"."lender_group_id" LEFT OUTER JOIN "document_loans" ON "document_loans"."document_id" = "documents"."id" LEFT OUTER JOIN "loans" ON "loans"."id" = "document_loans"."loan_id" WHERE (({:document_lender_groups=>{:lender_group_id=>[1]}}) OR ({:document_lenders=>{:lender_id=>1}}))
```

Here's the basics of my model setup:

``` ruby
class User
  belongs_to :lender
end

class Lender
  has_many :lender_groups
end

class LenderGroup
  has_many :lender_group_lenders
  has_many :lenders, through: :lender_group_lenders
end

class Document
  has_many :document_lenders
  has_many :document_lender_groups
  has_many :lenders, through: :document_lenders
  has_many :lender_groups, through: :document_lender_groups
end

class DocumentLender
  belongs_to :lender
  belongs_to :documents
end

```

Is it possible that this is an error? I can find some workarounds, but it would be great if this would work. Noticing the ruby at the end of the SQL statement leads me to believe that something isn't translating the ability into a SQL statement correctly - but I'm not sure.

Thanks!

**Comment by hallmatt** [comment] 2016-04-05 16:09
Any hopes on getting this fixed?

**Comment by tilast** [comment] 2016-04-12 13:09
approve, I have the similar issue =|
Rails 5.0.0.beta3
but same construction is still working nice with Rails 4.2.5.2

**Comment by tilast** [comment] 2016-04-12 13:30
actually the basic problem is because active record changed its api in v5.0.0.beta2
https://github.com/rails/rails/blob/4-2-stable/activerecord/lib/active_record/sanitization.rb#L22
https://github.com/rails/rails/blob/v5.0.0.beta2/activerecord/lib/active_record/sanitization.rb#L32

@hallmatt simple workaround that helped me - try to use strings instead of symbols like
```ruby
  can :read, Document, 'document_lenders' => { 'lender_id' => user.lender_id }
  can :read, Document, 'document_lender_groups' => { 'lender_group_id' => user.lender.lender_group_ids }
```

**Comment by rilian** [comment] 2016-05-22 13:04
cancancan (1.14.0) + postgres 9.5.3

```ruby
can :read, Pie, is_tasty: true, jam_id: nil
```
produces SQL
```sql
SELECT "pies".* FROM "pies" WHERE ({:is_tasty=>true, :jam_id=>nil})
```

while this
```ruby
can :read, Pie, ["is_tasty = 't' AND jam_id IS NULL"]
```

produces good SQL ..

**Comment by hallmatt** [comment] 2016-05-24 02:22
@rilian thanks for the follow up! I'll give it a shot.

**Comment by rilian** [comment] 2016-05-24 10:00
@hallmatt np, but please note that this is a workaround and it's not reliable. For example it does not work for checking abilities on instance...

I have ended up with writing abilities in that way that they do not require `OR`.

**Comment by tilast** [comment] 2016-05-24 10:31
@rilian @hallmatt my solution is just use `can :read, Entity, id: Entity.where(conditions).pluck(:id)`
looks like it works god

**Comment by alexsanford** [comment] 2016-08-20 17:52
@hallmatt Are you still having this issue on Rails 5? I'm unable to reproduce it on Rails 5.0.0 with CanCanCan version 1.14.0 or 1.15.0 and PostgreSQL 9.5.4. When I set up the models as you have and run `ability.model_adapter(Document, :index).conditions` I get:

```
"(\"document_lender_groups\".\"lender_group_id\" IN (1, 2, 3)) OR (\"document_lenders\".\"lender_id\" = 1)"
```

Which looks right to me...

**Comment by hallmatt** [comment] 2016-11-09 19:10
@alexsanford I was still having the issue. I ended up solving it a different way - so it's not as pressing for me anymore.

**Comment by brandon-carag** [comment] 2016-12-01 17:03
I was experiencing the same issue locally with Rails 5.0.0.1, CanCanCan 1.14.0, and PG 9.5.2.  Upgrading to CanCanCan 1.15.0 resolved the issue for me.

**Comment by coorasse** [comment] 2017-05-31 08:07
seems a duplicate of https://github.com/CanCanCommunity/cancancan/issues/410. I close this issue, feel free to reopen in case the problem persists. Thanks

**Closed by coorasse** 2017-05-31 08:07 UTC
