### ISSUE TITLE
Multiple relations as conditions are merged wrong

### ISSUE THREAD

**Issue by maxigs** [CanCanCommunity/cancancan#249] opened 2015-09-11 10:16 UTC
I have a  very interesting issue with cancancan. It has worked very good so far in a non-trivial project but now i have found a strange issue with how it merges conditions for a query.

I have the following Model Structure (Rails 4.2 with Active Record in MySQL):

```
class League
  has_one    :primary_league_organization, -> { where(primary: true) }, class_name: LeagueOrganization
  has_many   :league_organizations, -> { where(primary: false) }, class_name: LeagueOrganization
end

class LeagueOrganization
  belongs_to :league
  belongs_to, :context, polymorphic: true
end

# there are alternative classes, same structure for the polymorphic relationship
class Organization
  has_many :league_organizations, as: :context
  has_many :leagues, through: :league_organizations
end
```

With the following ability defined (simplified):

```
can :read, League, {league_organizations: {context_type: 'Organization', context_id: 6}}
can :read, League, {primary_league_organization: {context_type: 'Organization', context_id: 6}}
```

To either allow reading the League if the primary or any other Organization is related.

Which gives me this query, when accessing "League.all" with the cancancan scoping:

```
SELECT (...)
FROM `league_entries`
LEFT OUTER JOIN `league_organizations` ON `league_organizations`.`league_id` = `leagues`.`id` AND `league_organizations`.`primary` = 1
LEFT OUTER JOIN `league_organizations` `league_organizations_leagues` ON `league_organizations_leagues`.`league_id` = `leagues`.`id` AND `league_organizations_leagues`.`primary` = 0
WHERE (`league_organizations`.`context_type` = 'Organization' AND `league_organizations`.`context_id` = 6) OR (`league_organizations`.`context_type` = 'Organization' AND `league_organizations`.`context_id` = 6)
```

With the obvious problem that int he WHERE part the conditions are repeating itself, instead of using the different scopes the JOINs created.

The issue is similar in different places, but always with the same basic problem that the conditions in the query don't match the different scopes of the joins.

Since cancancan seems to just use the AR query builder i'm not really sure where to look for the issue here. Or if i rather start to change the way i handle this query or even the relationship in this case.

Any idea? I don't mind to put some effort into resolving this, but i'm not sure where to start or what direction is best.

**Comment by coorasse** [comment] 2018-06-22 12:12
duplicate of #337. closing.

**Closed by coorasse** 2018-06-22 12:12 UTC
