### ISSUE TITLE
Controller asks current_ability if it has been authorized

### ISSUE THREAD

**Issue by houen** [CanCanCommunity/cancancan#317] opened 2016-04-18 08:24 UTC
In our company we want to move the authorize! calls out of our controllers. Unfortunately this currently means we would have to give up check_authorization, since this currently relies on the instance var @_authorized being set on the controller.

I have opened a PR to address this: https://github.com/CanCanCommunity/cancancan/pull/316

The PR changes things so the controller asks the current_ability if it has had authorize! called. Now we can pass the current ability into other objects, and still use check_authorization in our controllers.

**Comment by Senjai** [comment] 2016-04-18 18:35
Duplicate of #316

**Closed by Senjai** 2016-04-18 18:35 UTC
