### ISSUE TITLE
Cancancan breaks belongs_to_required_by_default in Rails 5

### ISSUE THREAD

**Issue by DonMat** [CanCanCommunity/cancancan#342] opened 2016-08-11 15:54 UTC
In Rails 5 we have

> **#belongs_to is required by default**
> From now on every Rails application will have a new configuration option config.active_record.belongs_to_required_by_default = true, it will trigger a validation error when trying to save a model where belongs_to associations are not present.

I have cancancan 1.15.0 and it breaks default behavior so I still can save model with nil relation.
In case of that I have:

``` ruby
Rails.application.config.active_record.belongs_to_required_by_default
 => true 
ActiveRecord::Base.belongs_to_required_by_default
 => nil 
User.belongs_to_required_by_default
 => nil 
```

Without cancancan included to Gemfile

``` ruby
Rails.application.config.active_record.belongs_to_required_by_default
 => true 
ActiveRecord::Base.belongs_to_required_by_default
 => true 
User.belongs_to_required_by_default
 => true 
```

**Comment by alexsanford** [comment] 2016-08-14 17:57
Ok, it took some digging but I've figured out the problem and a fix. I haven't contributed to this project yet but with a little bit of guidance I'd be happy to write a test and submit a fix for this.

The problem is in the way the configuration is copied into ActiveRecord::Base. It's done in an `ActiveSupport.on_load(:active_record)` block (see https://github.com/rails/rails/blob/v5.0.0.1/activerecord/lib/active_record/railtie.rb#L111).

Normally, ActiveRecord is not fully loaded until after all initializers have been run, including the initializer that sets `Rails.application.config.active_record.belongs_to_required_by_default = true` (which you'll find in `config/initializers/new_framework_defaults.rb` in your app).

However, in CanCan, ActiveRecord is loaded early by the model adapter (see https://github.com/CanCanCommunity/cancancan/blob/develop/lib/cancan/model_adapters/active_record_adapter.rb#L146). This causes the configuration to be copied into ActiveRecord::Base before all of the initializers have been run.

I tested a solution locally. Wrapping the model adapter code in a call to `ActiveSupport.on_load(:active_record)` fixes it for me:

```
ActiveSupport.on_load(:active_record) do
  ActiveRecord::Base.class_eval do
    include CanCan::ModelAdditions
  end
end
```

Any thoughts? Again, I'm happy to try to put together a patch for this 😄

**Comment by Senjai** [comment] 2016-08-15 18:38
Please send in a patch @alexsanford thank you.

**Comment by alexsanford** [comment] 2016-08-17 10:49
FYI I closed my PR because it was a duplicate of #292. That PR should close this issue 😄

**Comment by jeromedalbert** [comment] 2016-08-26 11:12
Just for reference, this issue is related to https://github.com/rails/rails/issues/23589 .

**Comment by coorasse** [comment] 2017-04-06 06:46
Scheduled for version 2.0. I close this one. Thanks everyone.

**Closed by coorasse** 2017-04-06 06:46 UTC
