### ISSUE TITLE
Multiple definitions on same model broken after upgrading to Rails 5.2

### ISSUE THREAD

**Issue by andrewculver** [CanCanCommunity/cancancan#481] opened 2018-02-07 00:01 UTC
### Steps to reproduce

Given the following authorization:

```
      can :manage, Team, id: user.administrating_team_ids
      can :read, Team, id: user.team_ids
```

(Both `*_ids` methods return an array of IDs.)

There is a new error when we try to hit `teams#index` that worked previously.

### Expected behavior
It has historically worked fine and loaded `@teams` with the teams they can administrate as well as those they are only members of.

### Actual behavior
```
Error:
Account::TeamsControllerTest#test_should_get_index:
ActionView::Template::Error: PG::ProtocolViolation: ERROR:  bind message supplies 0 parameters, but prepared statement "" requires 2
: SELECT "teams".* FROM "teams" WHERE (("teams"."id" IN ($1, $2)) OR ("teams"."id" = $1))
    app/views/account/teams/index.html.erb:5:in `_app_views_account_teams_index_html_erb__2488223831243425059_70108490779980'
    test/controllers/account/teams_controller_test.rb:20:in `block in <class:TeamsControllerTest>'
```

In the example above, the user has one team they administrate and two teams they are members of, which is why the number of bind variables are what they are.

I think this is probably related to https://github.com/rails/rails/issues/20077 .

If I remove either of the definitions, the error goes away. It's only when I have two authorizations that the error occurs.

### System configuration
**Rails version**:
Rails 5.2.0-rc1

**Ruby version**:
Ruby 2.4.2

**CanCanCan version**
CanCanCan 2.0.0 or 2.1.3

**Comment by andrewculver** [comment] 2018-02-07 02:32
This issue is fixed by https://github.com/CanCanCommunity/cancancan/pull/479 , so it's probably a duplicate of https://github.com/CanCanCommunity/cancancan/issues/478 .

**Comment by coorasse** [comment] 2018-03-12 18:19
yes. duplicate of #478

**Closed by coorasse** 2018-03-12 18:19 UTC
