### ISSUE TITLE
using cancancan in active admin using rails 4.2.1

### ISSUE THREAD

**Issue by spurdow** [CanCanCommunity/cancancan#237] opened 2015-08-09 19:09 UTC
The problem lies with strong parameters, but i still dont get it why some solution doesnt work as stated in this blog. http://factore.ca/blog/258-rails-4-strong-parameters-and-cancan
if you want to test the project , please feel free to fork or clone -> https://github.com/jochun/lockout-ror
```ruby
class Ability
  include CanCan::Ability

  def initialize(user)
    case user.role
      when 'user'
        can :read, ActiveAdmin::Page, :name => "Dashboard"
        can :manage, Route, :company_id => user.company_id
        can :manage, BusRouteSchedule, :company_id => user.company_id
        can :read, Bus , :company_id => user.company_id
        can :manage, Conductor, :company_id => user.company_id
        can :manage, Station, :company_id => user.company_id

      when 'admin'
        can :read, ActiveAdmin::Page, :name => "Dashboard"
        can :manage, Route, :company_id => user.company_id
        can :manage, BusRouteSchedule, :company_id => user.company_id
        can :manage, Bus, :company_id => user.company_id
        can :manage, Conductor, :company_id => user.company_id
        can :manage, Station, :company_id => user.company_id
        can :manage, AdminUser, :company_id => user.company_id
      when 'super-admin'
        can :manage, :all
    end

  end
end
```
All of the user and admin roles cant create , is there any other work around with this?

**Comment by Fedcomp** [comment] 2015-12-02 15:01
You should try to specify rule block. Like this:
```ruby
can :update, AdminUser do |admin_user|
  admin_user.role.to_sym == :node_moderator || admin_user.id == admin.id
end
```

**Comment by DuBistKomisch** [comment] 2016-04-07 11:45
I ran into this exact issue and surprisingly couldn't find any direct solution for it out there. After reading cancancan, strong params, and activeadmin's docs, I found out you basically want to reimplement `new` and `create`, because by default they'll create the resource with `company_id: nil` in your case, which fails authorization because of your hash condition. You want to do something like this:

```
  [...]
  controller do
    [...]

    def new
      @route = build_resource
      # this checks that the user can create *a* route in general, otherwise refuse to render form at all
      authorize! :create, Route
      # don't seem to need to call super here, since it renders the form's view by default
    end

    def create
      @route = build_resource
      # this checks that the user can actually create the route as specified
      authorize! :create, @route
      # need to call super here to save and redirect
      super
    end

    def build_resource
      route = Route.new(permitted_params[:route])
      # put whatever logic you need here to satisfy your condition per role
      if current_user.role == 'admin'
        route.company = current_user.company
      end
      route
    end
  end
  [...]
```

This way, when `new` is called for generating the form, and when `create` is called by submitting the form, the authorization is satisfied.

Hope this helps.

**Comment by Fedcomp** [comment] 2016-04-07 12:04
@DuBistKomisch 
> I ran into this exact issue and surprisingly couldn't find any direct solution for it out there.
Active admin can use cancancan authorization if you specify it initializer. With builtin cancancan authorization module, and my rule block, activeadmin will not show links to edit to records you dont have access to.

**Comment by DuBistKomisch** [comment] 2016-04-07 12:22
@Fedcomp the issue is that creating resources fails with an authorisation error if your ability to create that resource is restricted with a hash condition. Everything else works more or less great out of the box.

**Comment by Senjai** [comment] 2016-08-07 08:33
Cancan really shouldn't be creating resources like that. It's out of scope of what the project should be doing, and the decision will hopefully be reversed down the road.

**Closed by Senjai** 2016-08-07 08:33 UTC

**Comment by DuBistKomisch** [comment] 2016-08-22 05:28
Yeah this was never an issue with cancancan, it's a limitation of activeadmin's adapter. :+1:

**Comment by davideghz** [comment] 2017-10-16 14:48
@DuBistKomisch thhx a lot for your input; now, what about the `update` action? Also, in order to save the model, I've been forced to allow mass assignment with `without_protection: true`

**Comment by DuBistKomisch** [comment] 2017-10-16 22:26
@davideghz I haven't run into any issues with update, only create. If you want to override it in general you can do:

```
  controller do
    def update
      @route = Route.find(params[:id])
      [...]
      super
    end
  end
```

I dunno why you would need to do that, are you using `permit_params` properly? I think you need to permit `:id` to do updates.
