### ISSUE TITLE
Wrong SQL for multiple abilities

### ISSUE THREAD

**Issue by koroboff54** [CanCanCommunity/cancancan#410] opened 2017-05-07 06:03 UTC
I have 2 conditions:
        can :read, Order, customer_from_id: user.role.customers.ids
        can :read, Order, customer_to_id: user.role.customers.ids

Error index page for orders:
PG::SyntaxError: ERROR:  syntax error at or near "{"
LINE 1: SELECT COUNT(*) FROM "orders" WHERE (({:customer_to_id=>[4, ...
                                              ^
: SELECT COUNT(*) FROM "orders" WHERE (({:customer_to_id=>[4, 2, 1]}) OR ({:customer_from_id=>[4, 2, 1]}))

with one ability everything fine:
SELECT COUNT(*) FROM "orders" WHERE "orders"."customer_from_id" IN (4, 2, 1)

need help

**Comment by coorasse** [comment] 2017-05-18 07:19
Which version of Rails are you using?

**Comment by koroboff54** [comment] 2017-05-23 01:42
ruby '2.4.0'
gem 'rails', '~> 5.1.0.rc2'

**Comment by coorasse** [comment] 2017-05-23 07:59
can you please also post the code that generates the wrong query? Does it look like `Order.accessible_by(current_ability, :read).count`? thanks

**Comment by coorasse** [comment] 2017-05-23 08:15
can you please update Rails to 5.1.0? I just tried your example and everything seems to work. Please look at this gist: https://gist.github.com/coorasse/0c0a773d2d215115cbd6161e9d4ddaf5 and edit it to reproduce the issue. Thanks

**Comment by koroboff54** [comment] 2017-05-24 03:28
code that generates wrong query is
Order.joins(:status).where(statuses: {is_final: true}).accessible_by(current_ability).size

**Comment by koroboff54** [comment] 2017-05-24 04:00
I was update to rails 5.1.0. your test https://gist.github.com/coorasse/0c0a773d2d215115cbd6161e9d4ddaf5 working fine for me
we are using postresql for project

**Comment by coorasse** [comment] 2017-05-24 05:54
are you able to write a similar test to reproduce your issue? Thanks

**Comment by koroboff54** [comment] 2017-05-29 02:42
it's working with rails 5.1.1, so updated and bug is gone

**Comment by coorasse** [comment] 2017-05-29 06:53
Thanks for the update. I close the issue. Feel free to reopen in case.

**Closed by coorasse** 2017-05-29 06:53 UTC
Labels: bug

**Comment by artlugovoy** [comment] 2019-01-25 22:12
Can still reproduce it on 2.3 had to downgrade to 1.5

**Comment by coorasse** [comment] 2019-01-26 08:17
@artlugovoy can you please open a new issue with the steps to reproduce the issue? Thank you! 🙏

**Comment by artlugovoy** [comment] 2019-01-26 12:50
@coorasse I tried to build up demo application with a same version of gems that are used in corporate application but I could not reproduce it. It just generates proper sql query. 

Sorry but I have not figured out much details to open up an issue just yet. Let's see if I can reproduce it later on by experimenting with potential gems\configs that could cause the sql error in corporate version of app.
